#!/bin/bash

RUND="/run"
ALTD="/var/run"


function help() {
	echo "A WiFi Connection Tool"
	echo -e "\nUsage: nwifictl -e <essid> -i <iface> [options]"
	echo "[options]:"
	echo -e "\t-e|-essid=[ESSID]\tSpecify the SSID to connect to "
	echo -e "\t-p|-psk=[PSK]\t\tSpecify the password"
	echo -e "\t-i|-iface=[IFACE]\tSpecify the interface to use"
	echo -e "\t-s|-spoof=[ADDR]\tSpoof interface MAC address"
	echo -e "\t-c|-config=[CONFIG]\tSpecify a custom wpa_supplicant config"
	echo -e "\t-help\t\t\tPrints this help text"

	exit 0
}

function connection_test() {
	# get local IP address
	local_ip=`ip addr |grep 'state UP' -A2 |tail -n1 |awk '{ print $2 }' |cut -d/ -f1`
	
	echo "Your local IP address is: $local_ip"
	echo "[*] Testing internet connection, this may take a few moments."
	
	# see if we can reach the interwebz
	ping -c1 -q 208.67.222.222 &>/dev/null

	if [ $? -eq 0 ]; then
		echo "[+] Successfully connected to $1"
	else
		echo "[-] Failed to connect to $1"
		exit 2
	fi
}

function connect() {
	# stop NetworkManager
	service NetworkManager stop 2>/dev/null

	# clean up old leases
	killall dhclient 2>/dev/null && killall wpa_supplicant 2>/dev/null
	rm $RUND/dhclient.pid 2>/dev/null && rm $ALTD/dhclient.pid
	rm $RUND/wpa_supplicant/$IFACE 2>/dev/null && rm $ALTD/wpa_supplicant/$IFACE 2>/dev/null

	if [ -z "$2" ]; then
	# if it's an open network

		# simple connect with iwconfig
		ip link set $4 down
		iwconfig $4 essid $1
		ip link set $4 up
	else
	# if it's a password-protected network

		# create and initialize config if it doesn't exist
		if [ ! -e "$3" ]; then
			touch $3
			echo -e "ctrl_interface=$RUND/wpa_supplicant\nctrl_interface_group=root\n" > $3
		fi

		# add network to the configuration file and initialize
		wpa_passphrase $1 $2 >> $3
		wpa_supplicant -B -Dnl80211 -i $4 -c $3 2>/dev/null
	fi
	
	# get an IP address from the AP
	dhclient $4 2>/dev/null

	echo "Waiting to finish connecting..."
	# wait for it to fully connect
	sleep 10

	# cheap workaround (will fix soon)
	echo nameserver 208.67.222.222 >> /etc/resolv.conf
}

# begin command-line parsing 
while [ "$1" != "" ]; do
	param=`echo $1|awk -F= '{print $1}'`
	value=`echo $1|awk -F= '{print $2}'`
	
	# help text
	if [ $1 == "-help" ]; then
		help
	fi

	case $param in
		-e|-essid)
			SSID=$value
		    	;;
		-p|-psk) 
			PASS="$value"
		    	;;
		-i|-iface) 
			IFACE=$value
		    	;;
		-s|-spoof)
			MAC=$value
			;;
		-c|-config)
			CONFIG=$value
			;;
		*) 
			echo "[!] $param is an incorrect option. See -help for more info."
		   	exit 1
		   	;;
	esac
	shift
done

# require -i option
if [ -z "$IFACE" ]; then
	echo "[!] You must specify an interface to use."
	exit 1
fi

# require -e option
if [ -z "$SSID" ]; then
	echo "[!] You must specify a network to connect to."
	exit 1
fi

# set default config if none specified
if [ -z "$CONFIG" ]; then
	CONFIG="/etc/wpa_supplicant.conf"	
fi

# spoof mac if -s option is specified
if [ -n "$MAC" ]; then
	ip link set $IFACE down
	ip link set dev $IFACE address $MAC
	ip link set $IFACE up
fi

# do stuff depending on auth or no auth
if [ -n "$PASS" ]; then
	echo "[*] Connecting to $SSID, this may take a few moments... "
	# if there is a password specified
	connect $SSID $PASS $CONFIG $IFACE
	connection_test $SSID
else
	echo "[*] Connecting to $SSID, this may take a few moments... "
	# if it's an open network
	connect $SSID "" $CONFIG $IFACE
	connection_test $SSID
fi

